#ifndef NUMERIC_H

#define NUMERIC_H

#define RPL_WELCOME "001"
#define RPL_TOPIC "332"
#define RPL_NAMREPLY "353"
#define RPL_ENDOFNAMES "366"
#define ERR_NICKNAMEINUSE "433"
#define ERR_NEEDMOREPARAMS "461"
#define ERR_ALREADYREGISTRED "462"
#define ERR_NONICKNAMEGIVEN "431"
#define ERR_ERRONEUSNICKNAME "432"
#define ERR_NOTONCHANNEL "442"
#define ERR_CHANOPRIVSNEEDED "482"
#define ERR_NOSUCHNICK "401"
#define ERR_NOSUCHCHANNEL "403"
#define ERR_USERONCHANNEL "443"
#define ERR_USERNOTINCHANNEL "441"





#define HOSTNAME ":127.0.0.1 "

#endif